/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *treeview2;
  GtkWidget *liste_des_avis_;
  GtkWidget *update;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12;
  GtkWidget *label5;
  GtkWidget *fixed2;
  GtkObject *day_adj;
  GtkWidget *day;
  GtkObject *month_adj;
  GtkWidget *month;
  GtkObject *year_adj;
  GtkWidget *year;
  GtkWidget *entry44;
  GtkWidget *entry222;
  GtkWidget *Reclamation_Date_;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *Parking_Name;
  GtkWidget *ID;
  GtkWidget *label25;
  GtkWidget *label54;
  GtkWidget *Rating_;
  GtkWidget *label55;
  GtkWidget *feedback;
  GtkWidget *label87;
  GtkWidget *check_Gmail;
  GtkWidget *check_sms;
  GtkWidget *Good;
  GSList *Good_group = NULL;
  GtkWidget *Medium;
  GtkWidget *Bad;
  GtkWidget *save;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label27;
  GtkWidget *button11;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label28;
  GtkWidget *label83;
  GtkWidget *combopark;
  GtkWidget *combonote;
  GtkWidget *label6;
  GtkWidget *fixed3;
  GtkObject *spinD_adj;
  GtkWidget *spinD;
  GtkObject *spinM_adj;
  GtkWidget *spinM;
  GtkObject *spinY_adj;
  GtkWidget *spinY;
  GtkWidget *entry3;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label77;
  GtkWidget *label76;
  GtkWidget *label75;
  GtkWidget *label82;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *entry223;
  GtkWidget *label105;
  GtkWidget *button13;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label42;
  GtkWidget *radio_g;
  GSList *radio_g_group = NULL;
  GtkWidget *radio_m;
  GtkWidget *radio_b;
  GtkWidget *check_G;
  GtkWidget *check_S;
  GtkWidget *label85;
  GtkWidget *send;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label41;
  GtkWidget *Find;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label84;
  GtkWidget *combo_p;
  GtkWidget *combo_n;
  GtkWidget *label7;
  GtkWidget *fixed4;
  GtkWidget *label47;
  GtkWidget *label106;
  GtkWidget *entry225;
  GtkWidget *treeview3;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *label107;
  GtkWidget *radiobutton2;
  GtkWidget *button15;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label52;
  GtkWidget *delete;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label108;
  GtkWidget *confirm;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label111;
  GtkWidget *OK;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label112;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label8;
  GtkWidget *fixed5;
  GtkWidget *label113;
  GtkWidget *empty_notebook_page;
  GtkWidget *label114;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);
  gtk_widget_set_size_request (fixed1, 680, 469);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview2, 88, 64);
  gtk_widget_set_size_request (treeview2, 608, 384);

  liste_des_avis_ = gtk_label_new (_("Citizen Feedback Liste"));
  gtk_widget_show (liste_des_avis_);
  gtk_fixed_put (GTK_FIXED (fixed1), liste_des_avis_, 272, 24);
  gtk_widget_set_size_request (liste_des_avis_, 192, 16);
  gtk_misc_set_alignment (GTK_MISC (liste_des_avis_), 0.33, 0.48);
  gtk_misc_set_padding (GTK_MISC (liste_des_avis_), 13, 0);

  update = gtk_button_new ();
  gtk_widget_show (update);
  gtk_fixed_put (GTK_FIXED (fixed1), update, 328, 480);
  gtk_widget_set_size_request (update, 88, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (update), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("UpDate\n"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("Home"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label5);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  day_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  day = gtk_spin_button_new (GTK_ADJUSTMENT (day_adj), 1, 0);
  gtk_widget_show (day);
  gtk_fixed_put (GTK_FIXED (fixed2), day, 208, 256);
  gtk_widget_set_size_request (day, 60, 27);

  month_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  month = gtk_spin_button_new (GTK_ADJUSTMENT (month_adj), 1, 0);
  gtk_widget_show (month);
  gtk_fixed_put (GTK_FIXED (fixed2), month, 264, 256);
  gtk_widget_set_size_request (month, 60, 27);

  year_adj = gtk_adjustment_new (1, 2022, 2030, 1, 10, 10);
  year = gtk_spin_button_new (GTK_ADJUSTMENT (year_adj), 1, 0);
  gtk_widget_show (year);
  gtk_fixed_put (GTK_FIXED (fixed2), year, 320, 256);
  gtk_widget_set_size_request (year, 60, 27);

  entry44 = gtk_entry_new ();
  gtk_widget_show (entry44);
  gtk_fixed_put (GTK_FIXED (fixed2), entry44, 208, 448);
  gtk_widget_set_size_request (entry44, 256, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry44), 8226);

  entry222 = gtk_entry_new ();
  gtk_widget_show (entry222);
  gtk_fixed_put (GTK_FIXED (fixed2), entry222, 200, 112);
  gtk_widget_set_size_request (entry222, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry222), 8226);

  Reclamation_Date_ = gtk_label_new (_("Reclamation  Date "));
  gtk_widget_show (Reclamation_Date_);
  gtk_fixed_put (GTK_FIXED (fixed2), Reclamation_Date_, 56, 264);
  gtk_widget_set_size_request (Reclamation_Date_, 144, 16);

  label72 = gtk_label_new (_("Day"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed2), label72, 208, 224);
  gtk_widget_set_size_request (label72, 49, 17);

  label73 = gtk_label_new (_("Month"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed2), label73, 264, 224);
  gtk_widget_set_size_request (label73, 49, 17);

  label74 = gtk_label_new (_("Year"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed2), label74, 328, 224);
  gtk_widget_set_size_request (label74, 49, 17);

  Parking_Name = gtk_label_new (_("Parking Name "));
  gtk_widget_show (Parking_Name);
  gtk_fixed_put (GTK_FIXED (fixed2), Parking_Name, 56, 184);
  gtk_widget_set_size_request (Parking_Name, 128, 16);

  ID = gtk_label_new (_("ID"));
  gtk_widget_show (ID);
  gtk_fixed_put (GTK_FIXED (fixed2), ID, 96, 120);
  gtk_widget_set_size_request (ID, 49, 17);

  label25 = gtk_label_new ("");
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 0, 328);
  gtk_widget_set_size_request (label25, 113, 16);

  label54 = gtk_label_new (_("PLease Add Your Review "));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed2), label54, 88, 24);
  gtk_widget_set_size_request (label54, 408, 64);

  Rating_ = gtk_label_new (_("Rating"));
  gtk_widget_show (Rating_);
  gtk_fixed_put (GTK_FIXED (fixed2), Rating_, 72, 328);
  gtk_widget_set_size_request (Rating_, 64, 16);

  label55 = gtk_label_new (_("Review  Type "));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed2), label55, 32, 384);
  gtk_widget_set_size_request (label55, 144, 25);

  feedback = gtk_label_new (_("\nEnter Your Feed Back"));
  gtk_widget_show (feedback);
  gtk_fixed_put (GTK_FIXED (fixed2), feedback, 40, 440);
  gtk_widget_set_size_request (feedback, 160, 40);

  label87 = gtk_label_new (_("Would you like to receive tracking by :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed2), label87, 40, 528);
  gtk_widget_set_size_request (label87, 264, 64);

  check_Gmail = gtk_check_button_new_with_mnemonic (_("Gmail"));
  gtk_widget_show (check_Gmail);
  gtk_fixed_put (GTK_FIXED (fixed2), check_Gmail, 312, 552);
  gtk_widget_set_size_request (check_Gmail, 118, 24);

  check_sms = gtk_check_button_new_with_mnemonic (_("SMS"));
  gtk_widget_show (check_sms);
  gtk_fixed_put (GTK_FIXED (fixed2), check_sms, 464, 552);
  gtk_widget_set_size_request (check_sms, 118, 24);

  Good = gtk_radio_button_new_with_mnemonic (NULL, _("Good"));
  gtk_widget_show (Good);
  gtk_fixed_put (GTK_FIXED (fixed2), Good, 184, 384);
  gtk_widget_set_size_request (Good, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Good), Good_group);
  Good_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Good));

  Medium = gtk_radio_button_new_with_mnemonic (NULL, _("Medium"));
  gtk_widget_show (Medium);
  gtk_fixed_put (GTK_FIXED (fixed2), Medium, 312, 384);
  gtk_widget_set_size_request (Medium, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Medium), Good_group);
  Good_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Medium));

  Bad = gtk_radio_button_new_with_mnemonic (NULL, _("Bad"));
  gtk_widget_show (Bad);
  gtk_fixed_put (GTK_FIXED (fixed2), Bad, 440, 384);
  gtk_widget_set_size_request (Bad, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Bad), Good_group);
  Good_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Bad));

  save = gtk_button_new ();
  gtk_widget_show (save);
  gtk_fixed_put (GTK_FIXED (fixed2), save, 176, 624);
  gtk_widget_set_size_request (save, 120, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (save), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Save changes \n\n"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox4), label27, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed2), button11, 400, 624);
  gtk_widget_set_size_request (button11, 88, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button11), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox5), label28, FALSE, FALSE, 0);

  label83 = gtk_label_new ("");
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed2), label83, 104, 688);
  gtk_widget_set_size_request (label83, 464, 17);

  combopark = gtk_combo_box_new_text ();
  gtk_widget_show (combopark);
  gtk_fixed_put (GTK_FIXED (fixed2), combopark, 200, 176);
  gtk_widget_set_size_request (combopark, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combopark), _("P1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combopark), _("P2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combopark), _("P3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combopark), _("P4"));

  combonote = gtk_combo_box_new_text ();
  gtk_widget_show (combonote);
  gtk_fixed_put (GTK_FIXED (fixed2), combonote, 200, 320);
  gtk_widget_set_size_request (combonote, 120, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combonote), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combonote), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combonote), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combonote), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combonote), _("5"));

  label6 = gtk_label_new (_("Add View"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label6);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  spinD_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinD = gtk_spin_button_new (GTK_ADJUSTMENT (spinD_adj), 1, 0);
  gtk_widget_show (spinD);
  gtk_fixed_put (GTK_FIXED (fixed3), spinD, 176, 184);
  gtk_widget_set_size_request (spinD, 60, 27);

  spinM_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spinM = gtk_spin_button_new (GTK_ADJUSTMENT (spinM_adj), 1, 0);
  gtk_widget_show (spinM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinM, 232, 184);
  gtk_widget_set_size_request (spinM, 60, 27);

  spinY_adj = gtk_adjustment_new (1, 2022, 2030, 1, 10, 10);
  spinY = gtk_spin_button_new (GTK_ADJUSTMENT (spinY_adj), 1, 0);
  gtk_widget_show (spinY);
  gtk_fixed_put (GTK_FIXED (fixed3), spinY, 280, 184);
  gtk_widget_set_size_request (spinY, 60, 27);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 160, 32);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label32 = gtk_label_new (_("Parking Name "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed3), label32, 32, 112);
  gtk_widget_set_size_request (label32, 128, 24);

  label33 = gtk_label_new (_("The Date "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed3), label33, 40, 184);
  gtk_widget_set_size_request (label33, 96, 16);

  label77 = gtk_label_new (_("Year"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed3), label77, 288, 160);
  gtk_widget_set_size_request (label77, 49, 17);

  label76 = gtk_label_new (_("Month"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed3), label76, 232, 160);
  gtk_widget_set_size_request (label76, 49, 17);

  label75 = gtk_label_new (_("Day"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed3), label75, 176, 160);
  gtk_widget_set_size_request (label75, 49, 17);

  label82 = gtk_label_new (_("Your  ID"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed3), label82, 48, 32);
  gtk_widget_set_size_request (label82, 72, 16);

  label102 = gtk_label_new (_("Rating"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed3), label102, 48, 240);
  gtk_widget_set_size_request (label102, 64, 16);

  label103 = gtk_label_new (_("Review  Type "));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed3), label103, 24, 304);
  gtk_widget_set_size_request (label103, 144, 25);

  label104 = gtk_label_new (_("\nEnter Your Feed Back"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed3), label104, 40, 352);
  gtk_widget_set_size_request (label104, 160, 40);

  entry223 = gtk_entry_new ();
  gtk_widget_show (entry223);
  gtk_fixed_put (GTK_FIXED (fixed3), entry223, 208, 360);
  gtk_widget_set_size_request (entry223, 256, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry223), 8226);

  label105 = gtk_label_new (_("Would you like to receive tracking by :"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed3), label105, 40, 440);
  gtk_widget_set_size_request (label105, 264, 64);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed3), button13, 272, 528);
  gtk_widget_set_size_request (button13, 88, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button13), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Home"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox9), label42, FALSE, FALSE, 0);

  radio_g = gtk_radio_button_new_with_mnemonic (NULL, _("Good"));
  gtk_widget_show (radio_g);
  gtk_fixed_put (GTK_FIXED (fixed3), radio_g, 176, 304);
  gtk_widget_set_size_request (radio_g, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_g), radio_g_group);
  radio_g_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_g));

  radio_m = gtk_radio_button_new_with_mnemonic (NULL, _("Medium"));
  gtk_widget_show (radio_m);
  gtk_fixed_put (GTK_FIXED (fixed3), radio_m, 256, 304);
  gtk_widget_set_size_request (radio_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_m), radio_g_group);
  radio_g_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_m));

  radio_b = gtk_radio_button_new_with_mnemonic (NULL, _("Bad"));
  gtk_widget_show (radio_b);
  gtk_fixed_put (GTK_FIXED (fixed3), radio_b, 360, 304);
  gtk_widget_set_size_request (radio_b, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_b), radio_g_group);
  radio_g_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_b));

  check_G = gtk_check_button_new_with_mnemonic (_("Gmail"));
  gtk_widget_show (check_G);
  gtk_fixed_put (GTK_FIXED (fixed3), check_G, 320, 464);
  gtk_widget_set_size_request (check_G, 118, 24);

  check_S = gtk_check_button_new_with_mnemonic (_("SMS"));
  gtk_widget_show (check_S);
  gtk_fixed_put (GTK_FIXED (fixed3), check_S, 408, 464);
  gtk_widget_set_size_request (check_S, 118, 24);

  label85 = gtk_label_new ("");
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed3), label85, 80, 568);
  gtk_widget_set_size_request (label85, 344, 32);

  send = gtk_button_new ();
  gtk_widget_show (send);
  gtk_fixed_put (GTK_FIXED (fixed3), send, 128, 528);
  gtk_widget_set_size_request (send, 80, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (send), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Send "));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox8), label41, FALSE, FALSE, 0);

  Find = gtk_button_new ();
  gtk_widget_show (Find);
  gtk_fixed_put (GTK_FIXED (fixed3), Find, 400, 32);
  gtk_widget_set_size_request (Find, 74, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (Find), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("Find"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox15), label84, FALSE, FALSE, 0);

  combo_p = gtk_combo_box_new_text ();
  gtk_widget_show (combo_p);
  gtk_fixed_put (GTK_FIXED (fixed3), combo_p, 160, 112);
  gtk_widget_set_size_request (combo_p, 96, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_p), _("P1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_p), _("P2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_p), _("P3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_p), _("P4"));

  combo_n = gtk_combo_box_new_text ();
  gtk_widget_show (combo_n);
  gtk_fixed_put (GTK_FIXED (fixed3), combo_n, 160, 232);
  gtk_widget_set_size_request (combo_n, 112, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_n), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_n), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_n), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_n), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_n), _("5"));

  label7 = gtk_label_new (_("Modify Review"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label7);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label47 = gtk_label_new (_("Your Feedback List"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 216, 16);
  gtk_widget_set_size_request (label47, 192, 16);
  gtk_misc_set_alignment (GTK_MISC (label47), 0.33, 0.48);
  gtk_misc_set_padding (GTK_MISC (label47), 13, 0);

  label106 = gtk_label_new (_("Enter Your ID"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed4), label106, 120, 56);
  gtk_widget_set_size_request (label106, 129, 16);

  entry225 = gtk_entry_new ();
  gtk_widget_show (entry225);
  gtk_fixed_put (GTK_FIXED (fixed4), entry225, 240, 48);
  gtk_widget_set_size_request (entry225, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry225), 8226);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview3, 48, 144);
  gtk_widget_set_size_request (treeview3, 609, 208);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("No"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton1, 352, 416);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label107 = gtk_label_new (_("Confirm the Deletion"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed4), label107, 0, 416);
  gtk_widget_set_size_request (label107, 232, 25);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Yes"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton2, 216, 416);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed4), button15, 344, 544);
  gtk_widget_set_size_request (button15, 74, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button15), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Home"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox13), label52, FALSE, FALSE, 0);

  delete = gtk_button_new ();
  gtk_widget_show (delete);
  gtk_fixed_put (GTK_FIXED (fixed4), delete, 168, 544);
  gtk_widget_set_size_request (delete, 74, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (delete), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox16), label108, FALSE, FALSE, 0);

  confirm = gtk_button_new ();
  gtk_widget_show (confirm);
  gtk_fixed_put (GTK_FIXED (fixed4), confirm, 264, 456);
  gtk_widget_set_size_request (confirm, 96, 24);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (confirm), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("confirm"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox17), label111, FALSE, FALSE, 0);

  OK = gtk_button_new ();
  gtk_widget_show (OK);
  gtk_fixed_put (GTK_FIXED (fixed4), OK, 456, 48);
  gtk_widget_set_size_request (OK, 74, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (OK), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox18), label112, FALSE, FALSE, 0);

  label109 = gtk_label_new ("");
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed4), label109, 136, 616);
  gtk_widget_set_size_request (label109, 360, 41);

  label110 = gtk_label_new ("");
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed4), label110, 184, 96);
  gtk_widget_set_size_request (label110, 304, 41);

  label8 = gtk_label_new (_("Delete Review"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label8);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  label113 = gtk_label_new ("");
  gtk_widget_show (label113);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label113);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label114 = gtk_label_new ("");
  gtk_widget_show (label114);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label114);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) update, "clicked",
                    G_CALLBACK (on_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) Good, "toggled",
                    G_CALLBACK (on_Good_toggled),
                    NULL);
  g_signal_connect ((gpointer) Medium, "toggled",
                    G_CALLBACK (on_Medium_toggled),
                    NULL);
  g_signal_connect ((gpointer) Bad, "toggled",
                    G_CALLBACK (on_Bad_toggled),
                    NULL);
  g_signal_connect ((gpointer) save, "clicked",
                    G_CALLBACK (on_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) send, "clicked",
                    G_CALLBACK (on_send_clicked),
                    NULL);
  g_signal_connect ((gpointer) Find, "clicked",
                    G_CALLBACK (on_Find_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete, "clicked",
                    G_CALLBACK (on_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirm, "clicked",
                    G_CALLBACK (on_confirm_clicked),
                    NULL);
  g_signal_connect ((gpointer) OK, "clicked",
                    G_CALLBACK (on_OK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, liste_des_avis_, "liste_des_avis_");
  GLADE_HOOKUP_OBJECT (window1, update, "update");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, day, "day");
  GLADE_HOOKUP_OBJECT (window1, month, "month");
  GLADE_HOOKUP_OBJECT (window1, year, "year");
  GLADE_HOOKUP_OBJECT (window1, entry44, "entry44");
  GLADE_HOOKUP_OBJECT (window1, entry222, "entry222");
  GLADE_HOOKUP_OBJECT (window1, Reclamation_Date_, "Reclamation_Date_");
  GLADE_HOOKUP_OBJECT (window1, label72, "label72");
  GLADE_HOOKUP_OBJECT (window1, label73, "label73");
  GLADE_HOOKUP_OBJECT (window1, label74, "label74");
  GLADE_HOOKUP_OBJECT (window1, Parking_Name, "Parking_Name");
  GLADE_HOOKUP_OBJECT (window1, ID, "ID");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");
  GLADE_HOOKUP_OBJECT (window1, Rating_, "Rating_");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, feedback, "feedback");
  GLADE_HOOKUP_OBJECT (window1, label87, "label87");
  GLADE_HOOKUP_OBJECT (window1, check_Gmail, "check_Gmail");
  GLADE_HOOKUP_OBJECT (window1, check_sms, "check_sms");
  GLADE_HOOKUP_OBJECT (window1, Good, "Good");
  GLADE_HOOKUP_OBJECT (window1, Medium, "Medium");
  GLADE_HOOKUP_OBJECT (window1, Bad, "Bad");
  GLADE_HOOKUP_OBJECT (window1, save, "save");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, label83, "label83");
  GLADE_HOOKUP_OBJECT (window1, combopark, "combopark");
  GLADE_HOOKUP_OBJECT (window1, combonote, "combonote");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, spinD, "spinD");
  GLADE_HOOKUP_OBJECT (window1, spinM, "spinM");
  GLADE_HOOKUP_OBJECT (window1, spinY, "spinY");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label77, "label77");
  GLADE_HOOKUP_OBJECT (window1, label76, "label76");
  GLADE_HOOKUP_OBJECT (window1, label75, "label75");
  GLADE_HOOKUP_OBJECT (window1, label82, "label82");
  GLADE_HOOKUP_OBJECT (window1, label102, "label102");
  GLADE_HOOKUP_OBJECT (window1, label103, "label103");
  GLADE_HOOKUP_OBJECT (window1, label104, "label104");
  GLADE_HOOKUP_OBJECT (window1, entry223, "entry223");
  GLADE_HOOKUP_OBJECT (window1, label105, "label105");
  GLADE_HOOKUP_OBJECT (window1, button13, "button13");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, radio_g, "radio_g");
  GLADE_HOOKUP_OBJECT (window1, radio_m, "radio_m");
  GLADE_HOOKUP_OBJECT (window1, radio_b, "radio_b");
  GLADE_HOOKUP_OBJECT (window1, check_G, "check_G");
  GLADE_HOOKUP_OBJECT (window1, check_S, "check_S");
  GLADE_HOOKUP_OBJECT (window1, label85, "label85");
  GLADE_HOOKUP_OBJECT (window1, send, "send");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, Find, "Find");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label84, "label84");
  GLADE_HOOKUP_OBJECT (window1, combo_p, "combo_p");
  GLADE_HOOKUP_OBJECT (window1, combo_n, "combo_n");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, label106, "label106");
  GLADE_HOOKUP_OBJECT (window1, entry225, "entry225");
  GLADE_HOOKUP_OBJECT (window1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window1, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, label107, "label107");
  GLADE_HOOKUP_OBJECT (window1, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, button15, "button15");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label52, "label52");
  GLADE_HOOKUP_OBJECT (window1, delete, "delete");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, label108, "label108");
  GLADE_HOOKUP_OBJECT (window1, confirm, "confirm");
  GLADE_HOOKUP_OBJECT (window1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label111, "label111");
  GLADE_HOOKUP_OBJECT (window1, OK, "OK");
  GLADE_HOOKUP_OBJECT (window1, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label112, "label112");
  GLADE_HOOKUP_OBJECT (window1, label109, "label109");
  GLADE_HOOKUP_OBJECT (window1, label110, "label110");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, label113, "label113");
  GLADE_HOOKUP_OBJECT (window1, label114, "label114");

  return window1;
}

